### ISSUE TITLE
Last steps before Demo 2

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#36]
I'll summurize the things we need to do before Monday:

- [x] Finish code review of the last stories completed
  - [x] Story 2
  - [x] Story 4
  - [x] Story 5
  - [x] Story 6 
- [x] Fix #35 
- [x] Fix current Database entries (most coordinates and points are wrong) #27 
- [x] Using story 2 add other 15 hikes (and so we test if it works)
- [x] If all works, merge story 2 into dev
- [x] Test if the new hikes are visible in story 4 branch (To resolve #32 )
- [x] If all works, merge story 4 into dev
- [x] Merge story 5 + test + #40 
- [x] Merge story 6 + test + possibles fixes 
- [x] Final test on dev
- [x] Docker
- [x] Prepare for demo (who presents what and how)

**Comment by FedeBel** [comment]
I try to fix the current points in the db
